# Generated by Django 3.1.7 on 2021-04-07 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='cverify',
            name='c_issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cverify',
            name='classwork',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='cverify',
            name='course',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='cverify',
            name='name',
            field=models.CharField(default='', max_length=122),
        ),
    ]
