# Generated by Django 3.1.7 on 2021-04-12 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210407_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cverify',
            name='cert_marks_gained',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='cverify',
            name='cert_max_marks',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='cverify',
            name='cert_pass_fail',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='cverify',
            name='coursecode',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='cverify',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
